app_index:
  path: /
  defaults: {_controller: "AppBundle:Default:index"}
  methods: [GET]

login:
  path: /login
  defaults: {_controller: "AppBundle:User:login"}

check_login:
  path: /check_login
  defaults: {_controller: "AppBundle:User:check"}

logout:
  path: /logout
  defaults: {_controller: "AppBundle:User:logout"}

open_index_user:
  path: /users
  defaults: {_controller: "AppBundle:User:index"}
  methods: [GET]

open_index_event:
  path: /events
  defaults: {_controller: "AppBundle:Event:index"}
  methods: [GET]
