app_index:
  path: /
  defaults: {_controller: "AppBundle:Default:index"}
  methods: [GET]

add_user:
  path: /users/add
  defaults: {_controller: "AppBundle:User:newUser"}
  methods: [GET, POST]

index_user:
  path: /users
  defaults: {_controller: "AppBundle:User:index"}
  methods: [GET]
