security:
    encoders:
        App\UserInterface\AppBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: {class: AppBundle:User}

    firewalls:
        main:
            switch_user: true
            pattern: /.*
            anonymous: true
            form_login:
                check_path: check_login
                login_path: login
                default_target_path: index_dashboard
            logout:
                path: logout
                target: app_index
            security: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
