parameters:

services:
  userFactory:
    class: App\Infrastructure\Application\Factory\UserFactory

  userRegistry:
    class: App\Infrastructure\Domain\UserRegistry

  userDataMapper:
    class: App\UserInterface\AppBundle\Services\UserDataMapper
    arguments:
      - "@userRegistry"
      - "@userFactory"
      - "@eventFactory"

  userRegistryGenerator:
    class: App\UserInterface\AppBundle\Services\UserRegistryGenerator
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@userDataMapper"
